import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiChatCircleTextDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiTypescript,
  SiZapier,
  SiOdoo,
  SiMeta,
  SiCanva,
  SiShopify,
  SiWordpress,
  SiNetlify,
  SiVercel,
  SiPython,
  SiGoogleanalytics,
  SiGooglesearchconsole,
  SiElevenlabs,
  SiDavinciresolve,
  SiGooglegemini,
  SiClaude,
} from "react-icons/si";

import { EMIcon } from "./EMIcon";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  brand: EMIcon,
  gallery: PiImageDuotone,
  message: PiChatCircleTextDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  typescript: SiTypescript,
  zapier: SiZapier,
  odoo: SiOdoo,
  meta: SiMeta,
  canva: SiCanva,
  shopify: SiShopify,
  wordpress: SiWordpress,
  netlify: SiNetlify,
  vercel: SiVercel,
  python: SiPython,
  googleAnalytics: SiGoogleanalytics,
  googleSearchConsole: SiGooglesearchconsole,
  elevenlabs: SiElevenlabs,
  davinciresolve: SiDavinciresolve,
  gemini: SiGooglegemini,
  claude: SiClaude,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
